hikey960: update tools-images-hikey960
Commit f9f39124efd1 ("hikey*: support migration to BL2_EL3 on arm-tf")
in build.git has changed the name of nvme.img to hisi-nvme.img, to
reflect the latest name used in upstream tools-images-hikey960.git, after
commit b5ae2c13438e ("installer: add hisi- prefix to ptable, sec_xloader,
fastboot, sec_uce_boot, and sec_usb_xloader imgs").
Unfortunately the HiKey960 manifest still references an older version of
the project, which causes an error during "make flash":

 $ make flash
 [...]
 fastboot flash nvme /home/jerome/work/optee_repo_hikey960/build/../tools-images-hikey960/hisi-nvme.img
 error: cannot load '/home/jerome/work/optee_repo_hikey960/build/../tools-images-hikey960/hisi-nvme.img'
 Makefile:322: recipe for target 'flash' failed
 make: *** [flash] Error 1

Fix this by updating tools-images-hikey960 in hikey960.xml (use the
current tip of the master branch).

Change-Id: Id1dd156fc2349079b6ec5575d62823e824843d7c
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>