qemuv8: use linaro-swg mirrors on GitHub for gitlab.arm.com projects
Use https://github.com/linaro-swg/SCP-firmware.git instead of
https://git.gitlab.arm.com/firmware/SCP-firmware.git and
https://github.com/linaro-swg/linux-trusted-services.git instead of
https://git.gitlab.arm.com/linux-arm/linux-trusted-services.git.

These mirrors will be maintained by Linaro (sync'ed with their
upstream) whenever this manifest needs updating to a new revision, but
likely not more often. The purpose of the mirrors is to deal with
reliability issues of https://git.gitlab.arm.com/. On March 4-5, 2025
We experienced HTTP 502 errors in the OP-TEE OS CI. On the other hand
GitHub has proved rock solid for years so let's switch to GitHub.

CI error log:

 repo has been initialized in /__w/optee_os/optee_repo_qemu_v8
 error: Cannot fetch firmware/SCP-firmware.git from https://git.gitlab.arm.com/firmware/SCP-firmware.git
 error: Cannot fetch firmware/SCP-firmware.git from https://git.gitlab.arm.com/firmware/SCP-firmware.git

 remote: GitLab is not responding
 fatal: unable to access 'https://git.gitlab.arm.com/firmware/SCP-firmware.git/': The requested URL returned error: 502

 firmware/SCP-firmware.git:
 remote: GitLab is not responding
 fatal: unable to access 'https://git.gitlab.arm.com/firmware/SCP-firmware.git/': The requested URL returned error: 502
 firmware/SCP-firmware.git: sleeping 4.0 seconds before retrying
 remote: GitLab is not responding
 fatal: unable to access 'https://git.gitlab.arm.com/firmware/SCP-firmware.git/': The requested URL returned error: 502
 error: Cannot checkout firmware/SCP-firmware.git: ManifestInvalidRevisionError: revision refs/tags/v2.15.0 in firmware/SCP-firmware.git not found
 error: in `sync -j20`: revision refs/tags/v2.15.0 in firmware/SCP-firmware.git not found

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>